consumer:
  brokers: ['192.168.0.105:9092']
  topic: 'delete.chat.message'
  group_id: 'consumer-delete-messages-group'

cache:
  address: '192.168.0.105'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  message_key_format: 'message.for.%s'
