consumer:
  brokers: ['192.168.0.64:9092']
  topic: 'delete.chat.message'
  group_id: 'consumer.delete.messages.group'

cache:
  address: '192.168.0.64'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  message_key_format: 'messages.for.%s'

health:
  port: ':8010'
  shutdown_endpoint: '/api/v1/consumer_delete_messages_health/shutdown'
  content_type: 'application/json'